
import type { Card } from './types';
import images from '@/app/lib/placeholder-images.json';

export const DECK: Card[] = [
  // PEOPLE
  { id: 'p01', name: 'Leonardo da Vinci', type: 'Person', description: 'Renaissance polymath: painter, sculptor, architect, inventor, and scientist.', imageUrl: images.renaissance, hint: 'renaissance polymath' },
  { id: 'p02', name: 'Marie Sklodowska-Curie', type: 'Person', description: 'Physicist and chemist who conducted pioneering research on radioactivity.', imageUrl: images.discovery_radium, hint: 'scientist marie curie' },
  { id: 'p03', name: 'Julius Caesar', type: 'Person', description: 'Roman general and statesman who played a critical role in the demise of the Roman Republic.', imageUrl: images.julius_caesar, hint: 'roman julius caesar' },
  { id: 'p04', name: 'Susan B. Anthony', type: 'Person', description: 'Social reformer and women\'s rights activist who played a pivotal role in the women\'s suffrage movement.', imageUrl: images.susan_b_anthony, hint: 'suffrage leader anthony' },
  { id: 'p05', name: 'Albert Einstein', type: 'Person', description: 'Theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics.', imageUrl: images.einstein, hint: 'physicist albert einstein' },
  { id: 'p06', name: 'Galileo Galilei', type: 'Person', description: 'Astronomer and physicist who played a major role in the scientific revolution.', imageUrl: images.galileo, hint: 'astronomer galileo' },
  { id: 'p07', name: 'Isaac Newton', type: 'Person', description: 'Key figure in the scientific revolution, known for formulating the laws of motion and universal gravitation.', imageUrl: images.newton, hint: 'scientist isaac newton' },
  { id: 'p08', name: 'Cleopatra', type: 'Person', description: 'The last active ruler of the Ptolemaic Kingdom of Egypt, known for her relationships with Roman leaders.', imageUrl: images.cleopatra, hint: 'egyptian queen cleopatra' },
  { id: 'p09', name: 'Martin Luther King Jr.', type: 'Person', description: 'Civil rights activist and minister who led the movement in the United States using nonviolence.', imageUrl: images.mlk, hint: 'civil rights leader king' },
  { id: 'p10', name: 'Queen Elizabeth I', type: 'Person', description: 'Queen of England and Ireland, the last of the Tudor monarchs, ruling during a golden age.', imageUrl: images.elizabeth_i, hint: 'tudor queen elizabeth' },
  { id: 'p11', name: 'Nikola Tesla', type: 'Person', description: 'Inventor best known for his contributions to the design of the AC electricity system.', imageUrl: images.tesla, hint: 'inventor nikola tesla' },
  { id: 'p12', name: 'Ada Lovelace', type: 'Person', description: 'Mathematician known for her work on Charles Babbage\'s early mechanical computer.', imageUrl: images.ada_lovelace, hint: 'first programmer lovelace' },
  { id: 'p13', name: 'Joan of Arc', type: 'Person', description: 'Heroine of France for her role during the Lancastrian phase of the Hundred Years\' War.', imageUrl: images.joan_of_arc, hint: 'historical joan arc' },
  { id: 'p14', name: 'Paul Revere', type: 'Person', description: 'American patriot best known for his midnight ride to alert the colonial militia.', imageUrl: images.shot_heard_round_world, hint: 'patriot paul revere' },
  { id: 'p15', name: 'Henry VIII', type: 'Person', description: 'King of England known for the English Reformation and his six marriages.', imageUrl: images.monarch, hint: 'tudor king henry' },
  { id: 'p16', name: 'Alexander the Great', type: 'Person', description: 'King of Macedon who created one of the largest empires of the ancient world.', imageUrl: images.alexander_great, hint: 'conqueror alexander macedon' },
  { id: 'p17', name: 'Harriet Tubman', type: 'Person', description: 'Abolitionist and political activist who led many to freedom on the Underground Railroad.', imageUrl: images.imprisonment_resistance, hint: 'abolitionist tubman' },
  { id: 'p18', name: 'Nelson Mandela', type: 'Person', description: 'Anti-apartheid revolutionary and the first black head of state in South Africa.', imageUrl: images.imprisonment_resistance, hint: 'nelson mandela revolutionary' },
  { id: 'p19', name: 'Winston Churchill', type: 'Person', description: 'Prime Minister of the UK who led the country to victory in World War II.', imageUrl: images.winston_churchill, hint: 'churchill uk leader' },
  { id: 'p20', name: 'Harry S Truman', type: 'Person', description: '33rd President of the US, who presided over the end of WWII and the start of the Cold War.', imageUrl: images.harry_truman, hint: 'president harry truman' },
  { id: 'p21', name: 'Mahatma Gandhi', type: 'Person', description: 'Leader of the Indian independence movement using nonviolent civil disobedience.', imageUrl: images.mahatma_gandhi, hint: 'leader mahatma gandhi' },
  { id: 'p22', name: 'Chief Sitting Bull', type: 'Person', description: 'Lakota leader who led his people during years of resistance against US policies.', imageUrl: images.chief_sitting_bull, hint: 'leader sitting bull' },
  { id: 'p23', name: 'Ulysses S. Grant', type: 'Person', description: 'Commanding General of the Union Army and 18th President of the United States.', imageUrl: images.ulysses_s_grant, hint: 'general ulysses grant' },
  { id: 'p24', name: 'Alexander Hamilton', type: 'Person', description: 'Founding Father and the first Secretary of the Treasury of the United States.', imageUrl: images.alexander_hamilton, hint: 'founding father hamilton' },
  { id: 'p25', name: 'John Adams', type: 'Person', description: 'Founding Father and the second President of the United States.', imageUrl: images.john_adams, hint: 'president john adams' },
  { id: 'p26', name: 'George Washington', type: 'Person', description: 'First President of the United States and Founding Father.', imageUrl: images.george_washington, hint: 'president george washington' },
  { id: 'p27', name: 'Thomas Jefferson', type: 'Person', description: 'Founding Father and the third President of the United States.', imageUrl: images.thomas_jefferson, hint: 'president thomas jefferson' },
  { id: 'p28', name: 'Benjamin Franklin', type: 'Person', description: 'Founding Father, polymath, and key figure in the American Enlightenment.', imageUrl: images.benjamin_franklin, hint: 'founding father franklin' },
  { id: 'p29', name: 'Theodore Roosevelt', type: 'Person', description: '26th President of the US, known for progressive reforms and conservation.', imageUrl: images.theodore_roosevelt, hint: 'president theo roosevelt' },
  { id: 'p30', name: 'James Madison', type: 'Person', description: 'Founding Father and the fourth President of the United States.', imageUrl: images.james_madison, hint: 'president james madison' },
  { id: 'p31', name: 'Dolley Madison', type: 'Person', description: 'First Lady known for her social influence and saving historical artifacts.', imageUrl: images.dolley_madison, hint: 'first lady dolley' },
  { id: 'p32', name: 'US President', type: 'Person', description: 'Representation of the executive office of the United States government.', imageUrl: images.us_president, hint: 'us president office' },
  { id: 'p33', name: 'Betsy Ross', type: 'Person', description: 'Credited with making the first official flag of the United States.', imageUrl: images.betsy_ross, hint: 'flag maker ross' },
  { id: 'p34', name: 'Jane Austen', type: 'Person', description: 'English novelist known for her realism, biting irony, and social commentary.', imageUrl: images.jane_austen, hint: 'novelist jane austen' },
  { id: 'p35', name: 'Charles Darwin', type: 'Person', description: 'Naturalist best known for his contributions to the science of evolution.', imageUrl: images.charles_darwin, hint: 'scientist charles darwin' },
  { id: 'p36', name: 'Vincent van Gogh', type: 'Person', description: 'Post-Impressionist painter who is among the most influential in Western art.', imageUrl: images.renaissance, hint: 'painter vincent gogh' },
  { id: 'p37', name: 'Rosa Parks', type: 'Person', description: 'Civil rights activist whose arrest sparked the Montgomery Bus Boycott.', imageUrl: images.montgomery_bus_boycott, hint: 'civil rights parks' },
  { id: 'p38', name: 'Sacagawea', type: 'Person', description: 'Lemhi Shoshone woman who helped the Lewis and Clark Expedition.', imageUrl: images.lewis_clark, hint: 'guide sacagawea historical' },
  { id: 'p39', name: 'George III', type: 'Person', description: 'King of Great Britain and Ireland during the American Revolution.', imageUrl: images.shot_heard_round_world, hint: 'king george iii' },
  { id: 'p40', name: 'Franklin D. Roosevelt', type: 'Person', description: '32nd US President, who led through the Great Depression and WWII.', imageUrl: images.franklin_roosevelt, hint: 'president fdr leader' },
  { id: 'p41', name: 'Aaron Burr', type: 'Person', description: 'Third US Vice President, who killed Alexander Hamilton in a duel.', imageUrl: images.aaron_burr, hint: 'vp aaron burr' },
  { id: 'p42', name: 'Eleanor Roosevelt', type: 'Person', description: 'First Lady and diplomat known for her advocacy of human rights.', imageUrl: images.eleanor_roosevelt, hint: 'human rights eleanor' },
  { id: 'p43', name: 'Hedy Lamarr', type: 'Person', description: 'Actress and inventor whose frequency-hopping technology led to Wi-Fi.', imageUrl: images.hedy_lamarr, hint: 'inventor hedy lamarr' },
  { id: 'p44', name: 'Rosalind Franklin', type: 'Person', description: 'Chemist whose X-ray images were key to discovering DNA\'s structure.', imageUrl: images.structure_dna, hint: 'scientist franklin dna' },
  { id: 'p45', name: 'Genghis Khan', type: 'Person', description: 'Founder and first Great Khan of the Mongol Empire.', imageUrl: images.alexander_great, hint: 'mongol leader genghis' },
  { id: 'p46', name: 'William Shakespeare', type: 'Person', description: 'English playwright and poet, widely regarded as the greatest in history.', imageUrl: images.renaissance, hint: 'playwright shakespeare' },
  { id: 'p47', name: 'Ferdinand Magellan', type: 'Person', description: 'Portuguese explorer who organized the first circumnavigation of the Earth.', imageUrl: images.patron_of_exploration, hint: 'explorer magellan' },
  { id: 'p48', name: 'Christopher Columbus', type: 'Person', description: 'Explorer whose voyages across the Atlantic opened the way for European exploration.', imageUrl: images.patron_of_exploration, hint: 'explorer columbus' },
  { id: 'p49', name: 'Neil Armstrong', type: 'Person', description: 'Astronaut and the first person to walk on the Moon.', imageUrl: images.manhattan_project, hint: 'astronaut armstrong' },
  { id: 'p50', name: 'Amelia Earhart', type: 'Person', description: 'Aviation pioneer and first female pilot to fly solo across the Atlantic.', imageUrl: images.golden_age_aviation, hint: 'pilot amelia earhart' },
  { id: 'p51', name: 'The Wright Brothers', type: 'Person', description: 'Orville and Wilbur Wright, inventors of the first successful airplane.', imageUrl: images.golden_age_aviation, hint: 'inventors wright brothers' },
  { id: 'p52', name: 'Marco Polo', type: 'Person', description: 'Venetian merchant explorer whose travels to Asia inspired many.', imageUrl: images.silk_road, hint: 'explorer marco polo' },
  { id: 'p53', name: 'Catherine the Great', type: 'Person', description: 'Empress of Russia who led the country into a golden age.', imageUrl: images.russian_empire, hint: 'empress catherine great' },
  { id: 'p54', name: 'Napoleon Bonaparte', type: 'Person', description: 'French military leader and emperor who conquered much of Europe.', imageUrl: images.emperor_france, hint: 'emperor napoleon bonaparte' },
  { id: 'p55', name: 'Sojourner Truth', type: 'Person', description: 'Abolitionist and women\'s rights activist known for her speech "Ain\'t I a Woman?".', imageUrl: images.imprisonment_resistance, hint: 'activist sojourner truth' },
  { id: 'p56', name: 'Frederick Douglass', type: 'Person', description: 'Social reformer and abolitionist who escaped slavery and became a leader.', imageUrl: images.imprisonment_resistance, hint: 'abolitionist frederick douglass' },
  { id: 'p57', name: 'Abraham Lincoln', type: 'Person', description: '16th US President, who preserved the Union and abolished slavery.', imageUrl: images.emancipation_proclamation, hint: 'president abraham lincoln' },

  // EVENTS
  { id: 'e01', name: 'The Renaissance', type: 'Event', description: 'A period of cultural, artistic, and scientific rebirth in Europe.', imageUrl: images.renaissance, hint: 'renaissance era' },
  { id: 'e02', name: 'Scientific Revolution', type: 'Event', description: 'Developments in mathematics and physics that transformed views of nature.', imageUrl: images.scientific_revolution, hint: 'scientific revolution' },
  { id: 'e03', name: 'Industrial Revolution', type: 'Event', description: 'The transition to new manufacturing processes in the 18th and 19th centuries.', imageUrl: images.industrial_rev, hint: 'industrial revolution' },
  { id: 'e04', name: 'Discovery of Radium', type: 'Event', description: 'The 1898 discovery by Marie and Pierre Curie of a new radioactive element.', imageUrl: images.discovery_radium, hint: 'discovery of radium' },
  { id: 'e05', name: 'Shot Heard Round the World', type: 'Event', description: 'The opening shot of the American Revolutionary War at Lexington.', imageUrl: images.shot_heard_round_world, hint: 'shot heard round' },
  { id: 'e06', name: 'Montgomery Bus Boycott', type: 'Event', description: 'A civil rights protest campaign against segregated public transit.', imageUrl: images.montgomery_bus_boycott, hint: 'bus boycott movement' },
  { id: 'e07', name: 'Imprisonment and Resistance', type: 'Event', description: 'The global struggle against oppression and unjust incarceration.', imageUrl: images.imprisonment_resistance, hint: 'resistance struggle' },
  { id: 'e08', name: 'The New Deal', type: 'Event', description: 'FDR\'s programs to provide relief, recovery, and reform after the Depression.', imageUrl: images.new_deal, hint: 'new deal programs' },
  { id: 'e09', name: 'Spanish Armada', type: 'Event', description: 'The Spanish fleet that attempted to invade England in 1588.', imageUrl: images.spanish_armada, hint: 'spanish armada fleet' },
  { id: 'e10', name: 'Federal Reserve Creation', type: 'Event', description: 'The 1913 establishment of the central banking system of the US.', imageUrl: images.federal_reserve_creation, hint: 'federal reserve creation' },
  { id: 'e11', name: 'Declaration of Independence', type: 'Event', description: 'The formal statement declaring the 13 colonies free from British rule.', imageUrl: images.declaration_independence, hint: 'declaration of independence' },
  { id: 'e12', name: 'Lewis and Clark Expedition', type: 'Event', description: 'The first American expedition to cross the western portion of the continent.', imageUrl: images.lewis_clark, hint: 'lewis clark expedition' },
  { id: 'e13', name: 'Salt March', type: 'Event', description: 'Nonviolent protest led by Gandhi against British colonial salt laws.', imageUrl: images.salt_march, hint: 'salt march protest' },
  { id: 'e14', name: 'Indian Independence Movement', type: 'Event', description: 'The series of events leading to the end of British rule in India.', imageUrl: images.indian_independence, hint: 'indian independence movement' },
  { id: 'e15', name: 'English Reformation', type: 'Event', description: 'The process by which the Church of England broke away from the Pope.', imageUrl: images.english_reformation, hint: 'english reformation' },
  { id: 'e16', name: 'Church of England', type: 'Event', description: 'The established Christian church in England, formed by Henry VIII.', imageUrl: images.church_of_england, hint: 'church of england' },
  { id: 'e17', name: 'European Conquests', type: 'Event', description: 'The expansion of European influence and territories globally.', imageUrl: images.european_conquests, hint: 'european conquests' },
  { id: 'e18', name: 'Emperor of France', type: 'Event', description: 'The title and reign of Napoleon Bonaparte over the French Empire.', imageUrl: images.emperor_france, hint: 'emperor of france' },
  { id: 'e19', name: 'Cultural Spread', type: 'Event', description: 'The diffusion of ideas, customs, and practices between societies.', imageUrl: images.cultural_spread, hint: 'cultural spread diffusion' },
  { id: 'e20', name: 'Empire Building', type: 'Event', description: 'The systematic expansion of a nation\'s territory and power.', imageUrl: images.empire_building_lh3, hint: 'empire building' },
  { id: 'e21', name: 'Cultural Power', type: 'Event', description: 'The influence exerted by a society through its culture and arts.', imageUrl: images.cultural_power, hint: 'cultural power influence' },
  { id: 'e22', name: 'Enlightenment Influence', type: 'Event', description: 'The impact of rationalist and humanist ideas on global society.', imageUrl: images.enlightenment_influence_lh3, hint: 'enlightenment influence' },
  { id: 'e23', name: 'Cold War Influence', type: 'Event', description: 'The global impact of the political tension between the US and USSR.', imageUrl: images.cold_war_influence, hint: 'cold war influence' },
  { id: 'e24', name: 'Nonviolent Resistance', type: 'Event', description: 'The practice of achieving social change through peaceful protest.', imageUrl: images.nonviolent_resistance, hint: 'nonviolent resistance' },
  { id: 'e25', name: 'Reconciliation', type: 'Event', description: 'The process of restoring peaceful relations after a period of conflict.', imageUrl: images.reconciliation, hint: 'reconciliation peace' },
  { id: 'e26', name: 'Russian Empire Expansion', type: 'Event', description: 'The territorial growth of the Russian state over several centuries.', imageUrl: images.russian_empire, hint: 'russian empire expansion' },
  { id: 'e27', name: 'Macedonian Conquests', type: 'Event', description: 'The expansion of the Greek empire under Alexander the Great.', imageUrl: images.macedonian_conquests, hint: 'macedonian conquests' },
  { id: 'e28', name: 'Duel', type: 'Event', description: 'A formal contest between two individuals to settle a point of honor.', imageUrl: images.duel, hint: 'historical duel' },
  { id: 'e29', name: 'Roman Alliances', type: 'Event', description: 'The network of treaties and partnerships that defined Roman power.', imageUrl: images.roman_alliances, hint: 'roman alliances' },
  { id: 'e30', name: 'Panama Canal', type: 'Event', description: 'The engineering feat connecting the Atlantic and Pacific oceans.', imageUrl: images.panama_canal, hint: 'panama canal' },
  { id: 'e31', name: 'Conservation', type: 'Event', description: 'The movement to protect natural resources and environmental heritage.', imageUrl: images.conservation, hint: 'conservation movement' },
  { id: 'e32', name: 'Native Resistance', type: 'Event', description: 'The defense of indigenous lands and culture against colonial expansion.', imageUrl: images.native_resistance, hint: 'native resistance' },
  { id: 'e33', name: 'Emancipation Proclamation', type: 'Event', description: 'The 1863 decree declaring the freedom of all enslaved people in rebel areas.', imageUrl: images.emancipation_proclamation, hint: 'emancipation proclamation' },
  { id: 'e34', name: 'Red Scare', type: 'Event', description: 'Periods of widespread fear of communist subversion in the US.', imageUrl: images.red_scare, hint: 'red scare history' },
  { id: 'e35', name: 'Draft', type: 'Event', description: 'Compulsory recruitment for military service.', imageUrl: images.draft_generic, hint: 'military draft' },
  { id: 'e36', name: 'Cuban Missile Crisis', type: 'Event', description: 'The 1962 confrontation between the US and USSR over missiles in Cuba.', imageUrl: images.cuban_missile_crisis, hint: 'missile crisis' },
  { id: 'e37', name: 'Vietnam War', type: 'Event', description: 'The major Cold War conflict in Southeast Asia.', imageUrl: images.vietnam_war, hint: 'vietnam war' },
  { id: 'e38', name: 'Crusades', type: 'Event', description: 'The religious wars between Christians and Muslims in the Middle Ages.', imageUrl: images.crusades, hint: 'medieval crusades' },
  { id: 'e39', name: 'World War I', type: 'Event', description: 'The global conflict that began in 1914 and reshaped modern history.', imageUrl: images.wwi, hint: 'world war one' },
  { id: 'e40', name: 'World War II', type: 'Event', description: 'The largest and most destructive global conflict in history.', imageUrl: images.manhattan_project, hint: 'world war two' },
  { id: 'e41', name: 'Golden Age of Aviation', type: 'Event', description: 'The period of rapid advancement in flight between the world wars.', imageUrl: images.golden_age_aviation, hint: 'aviation history' },
  { id: 'e42', name: 'The Silk Road', type: 'Event', description: 'The ancient network of trade routes connecting East and West.', imageUrl: images.silk_road, hint: 'silk road trade' },
  { id: 'e43', name: 'American Civil War', type: 'Event', description: 'The war fought between Northern and Southern states over slavery.', imageUrl: images.civil_war, hint: 'us civil war' },
  { id: 'e44', name: 'Women\'s Suffrage Movement', type: 'Event', description: 'The long struggle for women\'s right to vote.', imageUrl: images.womens_suffrage, hint: 'suffrage movement' },
  { id: 'e45', name: 'The Progressive Era', type: 'Event', description: 'A period of widespread social activism and political reform in the US.', imageUrl: images.progressive_era, hint: 'progressive era' },
  { id: 'e46', name: 'Globalization', type: 'Event', description: 'The process of integration and interaction among people worldwide.', imageUrl: images.globalization, hint: 'globalization world' },
  { id: 'e47', name: 'American Flag Creation', type: 'Event', description: 'The creation of the first official flag of the United States.', imageUrl: images.american_flag_creation, hint: 'us flag creation' },
  { id: 'e48', name: 'I Have a Dream Speech', type: 'Event', description: 'The iconic address delivered by MLK for jobs and freedom in 1963.', imageUrl: images.famous_speech, hint: 'dream speech history' },
  { id: 'e49', name: 'UN Advocacy', type: 'Event', description: 'The promotion of international cooperation through the United Nations.', imageUrl: images.un_advocacy, hint: 'united nations advocacy' },
  { id: 'e50', name: 'Atomic Bomb Decisions', type: 'Event', description: 'The complex choices surrounding the use of nuclear weapons in WWII.', imageUrl: images.atomic_bomb_decisions, hint: 'atomic bomb decisions' },
  { id: 'e51', name: 'Early Republic Politics', type: 'Event', description: 'The political development and struggles of the early United States.', imageUrl: images.early_republic_politics, hint: 'early us politics' },
  { id: 'e52', name: 'American Revolution', type: 'Event', description: 'The war for independence of the 13 colonies from Great Britain.', imageUrl: images.american_revolution, hint: 'american revolution' },
  { id: 'e53', name: 'Constitution', type: 'Event', description: 'The creation and signing of the supreme law of the United States.', imageUrl: images.constitution, hint: 'us constitution' },
  { id: 'e54', name: 'Treasury System', type: 'Event', description: 'The establishment of the US financial framework by Hamilton.', imageUrl: images.treasury_system, hint: 'us treasury system' },
  { id: 'e55', name: 'Federalist Papers', type: 'Event', description: 'Essays written to promote the ratification of the US Constitution.', imageUrl: images.constitution, hint: 'federalist papers' },
  { id: 'e56', name: 'Structure of DNA', type: 'Event', description: 'The discovery of the double helix structure by Watson and Crick.', imageUrl: images.structure_dna, hint: 'dna structure discovery' },
  { id: 'e57', name: 'Regency Era', type: 'Event', description: 'A period in British history known for its distinct culture and elegance.', imageUrl: images.regency_era, hint: 'regency era history' },
  { id: 'e58', name: 'Crossing the Rubicon', type: 'Event', description: 'Caesar\'s decisive move that signaled the end of the Roman Republic.', imageUrl: images.julius_caesar, hint: 'crossing rubicon caesar' },
  { id: 'e59', name: 'Ptolemaic Dynasty', type: 'Event', description: 'The Greek royal family that ruled Egypt for nearly 300 years.', imageUrl: images.cleopatra, hint: 'ptolemaic dynasty egypt' },
  { id: 'e60', name: 'March on Washington', type: 'Event', description: 'The massive civil rights rally for jobs and freedom in 1963.', imageUrl: images.mlk, hint: 'march on washington' },
  { id: 'e61', name: 'War of the Currents', type: 'Event', description: 'The battle between Tesla and Edison over AC vs. DC electricity.', imageUrl: images.tesla, hint: 'war of currents' },
  { id: 'e62', name: 'Analytical Engine', type: 'Event', description: 'The design of a general-purpose mechanical computer by Babbage.', imageUrl: images.ada_lovelace, hint: 'analytical engine computer' },
  { id: 'e63', name: 'The Copernican Model', type: 'Event', description: 'The heliocentric model of the universe proposed by Copernicus.', imageUrl: images.galileo, hint: 'copernican model' },
  { id: 'e64', name: 'The Mongol Empire', type: 'Event', description: 'The largest contiguous land empire in history founded by Genghis Khan.', imageUrl: images.alexander_great, hint: 'mongol empire history' },
  { id: 'e65', name: 'Frequency Hopping', type: 'Event', description: 'The invention of secure communication technology by Hedy Lamarr.', imageUrl: images.manhattan_project, hint: 'frequency hopping tech' },
  { id: 'e66', name: 'The Globe Theatre', type: 'Event', description: 'The theater associated with William Shakespeare and his plays.', imageUrl: images.renaissance, hint: 'globe theatre history' },
  { id: 'e67', name: 'Age of Discovery', type: 'Event', description: 'The period of extensive global exploration by European nations.', imageUrl: images.patron_of_exploration, hint: 'age of discovery' },
  { id: 'e68', name: 'Apollo 11 Mission', type: 'Event', description: 'The historic mission that first landed humans on the Moon.', imageUrl: images.manhattan_project, hint: 'apollo 11 moon' },
  { id: 'e69', name: 'Post-Impressionism', type: 'Event', description: 'The French art movement that followed Impressionism.', imageUrl: images.renaissance, hint: 'post-impressionism art' },

  // WILDCARDS
  { id: 'w01', name: 'Revolution Wildcard', type: 'Wildcard', description: 'This Person was part of or assisted a Revolution.', imageUrl: images.wildcard_revolution, hint: 'revolution wildcard' }
];
