import type { Card } from './types';

export const DECK: Card[] = [
  // People
  {
    id: 'p01',
    name: 'Leonardo da Vinci',
    type: 'Person',
    description: 'A true Renaissance man, excelling in painting, sculpture, architecture, music, science, and more.',
    imageUrl: 'https://picsum.photos/seed/da_vinci/500/500',
    hint: 'renaissance artist',
  },
  {
    id: 'p02',
    name: 'Marie Sklodowska-Curie',
    type: 'Person',
    description: 'A physicist and chemist who conducted pioneering research on radioactivity. The first woman to win a Nobel Prize.',
    imageUrl: 'https://picsum.photos/seed/curie/500/500',
    hint: 'pioneering scientist',
  },
  {
    id: 'p03',
    name: 'Julius Caesar',
    type: 'Person',
    description: 'A Roman general and statesman who played a critical role in the events that led to the demise of the Roman Republic.',
    imageUrl: 'https://picsum.photos/seed/caesar/500/500',
    hint: 'roman emperor',
  },
  {
    id: 'p04',
    name: 'Cleopatra',
    type: 'Person',
    description: 'The last active ruler of the Ptolemaic Kingdom of Egypt, known for her intelligence and political acumen.',
    imageUrl: 'https://picsum.photos/seed/cleopatra/500/500',
    hint: 'egyptian queen',
  },
  {
    id: 'p05',
    name: 'Albert Einstein',
    type: 'Person',
    description: 'Developed the theory of relativity, one of the two pillars of modern physics.',
    imageUrl: 'https://picsum.photos/seed/einstein/500/500',
    hint: 'modern physicist',
  },
  {
    id: 'p06',
    name: 'Isaac Newton',
    type: 'Person',
    description: 'An English mathematician, physicist, and astronomer, widely recognized as one of the most influential scientists of all time.',
    imageUrl: 'https://picsum.photos/seed/newton/500/500',
    hint: 'influential scientist',
  },
  {
    id: 'p07',
    name: 'Martin Luther King Jr.',
    type: 'Person',
    description: 'An American Baptist minister and activist who became the most visible spokesperson in the civil rights movement.',
    imageUrl: 'https://picsum.photos/seed/mlk/500/500',
    hint: 'civil rights',
  },
  {
    id: 'p08',
    name: 'Queen Elizabeth I',
    type: 'Person',
    description: 'Queen of England and Ireland from 1558 until her death in 1603. Sometimes called the Virgin Queen.',
    imageUrl: 'https://picsum.photos/seed/elizabeth_i/500/500',
    hint: 'english monarch',
  },
  {
    id: 'p09',
    name: 'Nikola Tesla',
    type: 'Person',
    description: 'A Serbian-American inventor and engineer best known for his contributions to the design of the modern AC electricity system.',
    imageUrl: 'https://picsum.photos/seed/tesla/500/500',
    hint: 'inventor engineer',
  },
  {
    id: 'p10',
    name: 'Ada Lovelace',
    type: 'Person',
    description: "An English mathematician and writer, chiefly known for her work on Charles Babbage's proposed mechanical computer.",
    imageUrl: 'https://picsum.photos/seed/lovelace/500/500',
    hint: 'computer pioneer',
  },
  {
    id: 'p11',
    name: 'Galileo Galilei',
    type: 'Person',
    description: 'An Italian astronomer, physicist and engineer, whose discoveries with the telescope revolutionized astronomy.',
    imageUrl: 'https://picsum.photos/seed/galileo/500/500',
    hint: 'astronomer physicist',
  },
  {
    id: 'p12',
    name: 'Joan of Arc',
    type: 'Person',
    description: 'A peasant girl who, believing that she was acting under divine guidance, led the French army in a momentous victory at Orléans.',
    imageUrl: 'https://picsum.photos/seed/joan_of_arc/500/500',
    hint: 'french heroine',
  },
  {
    id: 'p13',
    name: 'Paul Revere',
    type: 'Person',
    description: 'An American silversmith and Patriot in the American Revolution, famous for his midnight ride to alert colonial militia of British forces.',
    imageUrl: 'https://picsum.photos/seed/revere/500/500',
    hint: 'american patriot',
  },
  {
    id: 'p14',
    name: 'Henry VIII',
    type: 'Person',
    description: 'King of England from 1509 until his death, famously married six times and was a central figure in the English Reformation.',
    imageUrl: 'https://picsum.photos/seed/henry_viii/500/500',
    hint: 'english king',
  },
  {
    id: 'p15',
    name: 'Abraham Lincoln',
    type: 'Person',
    description: '16th President of the United States, who led the country through the Civil War and abolished slavery.',
    imageUrl: 'https://picsum.photos/seed/lincoln/500/500',
    hint: 'us president',
  },
  {
    id: 'p16',
    name: 'Frederick Douglass',
    type: 'Person',
    description: 'An American social reformer, abolitionist, orator, writer, and statesman. After escaping from slavery, he became a national leader of the abolitionist movement.',
    imageUrl: 'https://picsum.photos/seed/douglass/500/500',
    hint: 'abolitionist leader',
  },
  {
    id: 'p17',
    name: 'Alexander the Great',
    type: 'Person',
    description: 'A king of the ancient Greek kingdom of Macedon, he created one of the largest empires of the ancient world.',
    imageUrl: 'https://picsum.photos/seed/alexander/500/500',
    hint: 'ancient conqueror',
  },
  {
    id: 'p18',
    name: 'Sojourner Truth',
    type: 'Person',
    description: "An African-American abolitionist and women's rights activist. Truth was born into slavery but escaped with her infant daughter to freedom in 1826.",
    imageUrl: 'https://picsum.photos/seed/truth/500/500',
    hint: 'abolitionist activist',
  },
  {
    id: 'p19',
    name: 'Harriet Tubman',
    type: 'Person',
    description: 'An American abolitionist and political activist. Born into slavery, Tubman escaped and subsequently made some thirteen missions to rescue approximately seventy enslaved people.',
    imageUrl: 'https://picsum.photos/seed/tubman/500/500',
    hint: 'abolitionist activist',
  },
  {
    id: 'p20',
    name: 'Nelson Mandela',
    type: 'Person',
    description: 'A South African anti-apartheid revolutionary, political leader and philanthropist who served as President of South Africa from 1994 to 1999.',
    imageUrl: 'https://picsum.photos/seed/mandela/500/500',
    hint: 'political leader',
  },
  {
    id: 'p21',
    name: 'Winston Churchill',
    type: 'Person',
    description: 'A British statesman, soldier and writer who served as Prime Minister of the United Kingdom from 1940 to 1945, during the Second World War, and again from 1951 to 1955.',
    imageUrl: 'https://picsum.photos/seed/churchill/500/500',
    hint: 'british statesman',
  },
  {
    id: 'p22',
    name: 'Genghis Khan',
    type: 'Person',
    description: 'The founder and first Great Khan of the Mongol Empire, which became the largest contiguous empire in history after his death.',
    imageUrl: 'https://picsum.photos/seed/khan/500/500',
    hint: 'mongol emperor',
  },
  {
    id: 'p23',
    name: 'Rosalind Franklin',
    type: 'Person',
    description: 'An English chemist and X-ray crystallographer whose work was central to the understanding of the molecular structures of DNA, RNA, viruses, coal, and graphite.',
    imageUrl: 'https://picsum.photos/seed/rosalind_franklin/500/500',
    hint: 'english chemist',
  },
  {
    id: 'p24',
    name: 'Hedy Lamarr',
    type: 'Person',
    description: 'An Austrian-born American actress, inventor, and film producer. She was a co-inventor of an early version of frequency-hopping spread spectrum communication.',
    imageUrl: 'https://picsum.photos/seed/lamarr/500/500',
    hint: 'actress inventor',
  },
  {
    id: 'p25',
    name: 'Napoleon Bonaparte',
    type: 'Person',
    description: 'A French military and political leader who rose to prominence during the French Revolution and led several successful campaigns during the Revolutionary Wars.',
    imageUrl: 'https://picsum.photos/seed/napoleon/500/500',
    hint: 'french emperor',
  },
  {
    id: 'p26',
    name: 'William Shakespeare',
    type: 'Person',
    description: 'An English playwright, poet, and actor, widely regarded as the greatest writer in the English language and the world\'s greatest dramatist.',
    imageUrl: 'https://picsum.photos/seed/shakespeare/500/500',
    hint: 'english playwright',
  },
  {
    id: 'p27',
    name: 'Ferdinand Magellan',
    type: 'Person',
    description: 'A Portuguese explorer who organised the Spanish expedition to the East Indies from 1519 to 1522, resulting in the first circumnavigation of the Earth.',
    imageUrl: 'https://picsum.photos/seed/magellan/500/500',
    hint: 'portuguese explorer',
  },
  {
    id: 'p28',
    name: 'Christopher Columbus',
    type: 'Person',
    description: 'An Italian explorer and navigator who completed four voyages across the Atlantic Ocean, opening the way for European exploration and colonization of the Americas.',
    imageUrl: 'https://picsum.photos/seed/columbus/500/500',
    hint: 'italian explorer',
  },
  {
    id: 'p29',
    name: 'John F. Kennedy',
    type: 'Person',
    description: 'An American politician who served as the 35th president of the United States from 1961 until his assassination in 1963.',
    imageUrl: 'https://picsum.photos/seed/jfk/500/500',
    hint: 'american president',
  },
  {
    id: 'p30',
    name: 'Neil Armstrong',
    type: 'Person',
    description: 'An American astronaut and aeronautical engineer, and the first person to walk on the Moon.',
    imageUrl: 'https://picsum.photos/seed/armstrong/500/500',
    hint: 'american astronaut',
  },
  {
    id: 'p31',
    name: 'Amelia Earhart',
    type: 'Person',
    description: 'An American aviation pioneer and author. Earhart was the first female aviator to fly solo across the Atlantic Ocean.',
    imageUrl: 'https://picsum.photos/seed/earhart/500/500',
    hint: 'aviation pioneer',
  },
  {
    id: 'p32',
    name: 'The Wright Brothers',
    type: 'Person',
    description: 'Two American aviation pioneers generally credited with inventing, building, and flying the world\'s first successful motor-operated airplane.',
    imageUrl: 'https://picsum.photos/seed/wright_brothers/500/500',
    hint: 'aviation pioneers',
  },
  {
    id: 'p33',
    name: 'Marco Polo',
    type: 'Person',
    description: 'A Venetian merchant, explorer, and writer who travelled through Asia along the Silk Road between 1271 and 1295.',
    imageUrl: 'https://picsum.photos/seed/polo/500/500',
    hint: 'venetian merchant',
  },
  {
    id: 'p34',
    name: 'Alexander Hamilton',
    type: 'Person',
    description: 'An American statesman, politician, legal scholar, military commander, lawyer, banker, and economist. He was one of the Founding Fathers of the United States.',
    imageUrl: 'https://picsum.photos/seed/hamilton/500/500',
    hint: 'founding father',
  },
  {
    id: 'p35',
    name: 'Thomas Jefferson',
    type: 'Person',
    description: 'An American statesman, diplomat, lawyer, architect, philosopher, and Founding Father who served as the third president of the United States from 1801 to 1809.',
    imageUrl: 'https://picsum.photos/seed/jefferson/500/500',
    hint: 'american statesman',
  },
  {
    id: 'p36',
    name: 'Ulysses S. Grant',
    type: 'Person',
    description: 'An American general and the 18th president of the United States (1869–1877). He led the Union Army as Commanding General of the United States Army in winning the American Civil War.',
    imageUrl: 'https://picsum.photos/seed/grant/500/500',
    hint: 'american general',
  },
  {
    id: 'p37',
    name: 'Franklin D. Roosevelt',
    type: 'Person',
    description: 'An American politician who served as the 32nd president of the United States from 1933 until his death in 1945.',
    imageUrl: 'https://picsum.photos/seed/fdr/500/500',
    hint: '32nd president',
  },
  {
    id: 'p38',
    name: 'Susan B. Anthony',
    type: 'Person',
    description: 'An American social reformer and women\'s rights activist who played a pivotal role in the women\'s suffrage movement.',
    imageUrl: 'https://picsum.photos/seed/susan_b_anthony/500/500',
    hint: 'social reformer',
  },
  {
    id: 'p39',
    name: 'Jane Austen',
    type: 'Person',
    description: 'An English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century.',
    imageUrl: 'https://picsum.photos/seed/austen/500/500',
    hint: 'english novelist',
  },
  {
    id: 'p40',
    name: 'Charles Darwin',
    type: 'Person',
    description: 'An English naturalist, geologist and biologist, best known for his contributions to the science of evolution.',
    imageUrl: 'https://picsum.photos/seed/darwin/500/500',
    hint: 'english naturalist',
  },
  {
    id: 'p41',
    name: 'Vincent van Gogh',
    type: 'Person',
    description: 'A Dutch Post-Impressionist painter who is among the most famous and influential figures in the history of Western art.',
    imageUrl: 'https://picsum.photos/seed/van_gogh/500/500',
    hint: 'dutch painter',
  },
  {
    id: 'p42',
    name: 'Theodore Roosevelt',
    type: 'Person',
    description: 'An American statesman, politician, conservationist, naturalist, and writer who served as the 26th president of the United States from 1901 to 1909.',
    imageUrl: 'https://picsum.photos/seed/teddy_roosevelt/500/500',
    hint: '26th president',
  },
  {
    id: 'p43',
    name: 'Catherine the Great',
    type: 'Person',
    description: 'The last reigning Empress Regnant of Russia and the country\'s longest-ruling female leader.',
    imageUrl: 'https://picsum.photos/seed/catherine/500/500',
    hint: 'russian empress',
  },
  {
    id: 'p44',
    name: 'Eleanor Roosevelt',
    type: 'Person',
    description: 'An American political figure, diplomat and activist. She served as the first lady of the United States from 1933 to 1945.',
    imageUrl: 'https://picsum.photos/seed/eleanor_roosevelt/500/500',
    hint: 'first lady',
  },
  {
    id: 'p45',
    name: 'Benjamin Franklin',
    type: 'Person',
    description: 'One of the Founding Fathers of the United States. A polymath, he was a leading writer, printer, political philosopher, politician, Freemason, postmaster, scientist, inventor, humorist, civic activist, statesman, and diplomat.',
    imageUrl: 'https://picsum.photos/seed/ben_franklin/500/500',
    hint: 'founding polymath',
  },
  {
    id: 'p46',
    name: 'Sacagawea',
    type: 'Person',
    description: 'A Lemhi Shoshone woman who, at age 16, helped the Lewis and Clark Expedition in achieving their chartered mission objectives by exploring the Louisiana Territory.',
    imageUrl: 'https://picsum.photos/seed/sacagawea/500/500',
    hint: 'native american',
  },
  {
    id: 'p47',
    name: 'Rosa Parks',
    type: 'Person',
    description: 'An activist in the civil rights movement best known for her pivotal role in the Montgomery bus boycott.',
    imageUrl: 'https://picsum.photos/seed/rosa_parks/500/500',
    hint: 'civil rights',
  },
  {
    id: 'p48',
    name: 'President (generic)',
    type: 'Person',
    description: 'Represents any President of a country. Their leadership and decisions can shape the course of history.',
    imageUrl: 'https://picsum.photos/seed/president/500/500',
    hint: 'generic president',
  },
  {
    id: 'p49',
    name: 'Betsy Ross',
    type: 'Person',
    description: 'An American upholsterer who was credited by her relatives in 1870 with making the first American flag.',
    imageUrl: 'https://picsum.photos/seed/betsy_ross/500/500',
    hint: 'american flag',
  },
  {
    id: 'p50',
    name: 'Aaron Burr',
    type: 'Person',
    description: 'An American politician and lawyer. He served as the third vice president of the United States during President Thomas Jefferson\'s first term.',
    imageUrl: 'https://picsum.photos/seed/burr/500/500',
    hint: 'third vp',
  },
  {
    id: 'p51',
    name: 'Dolley Madison',
    type: 'Person',
    description: 'The wife of James Madison, the fourth president of the United States. She was noted for her social graces, which boosted her husband\'s popularity as president.',
    imageUrl: 'https://picsum.photos/seed/dolley/500/500',
    hint: 'first lady',
  },
  {
    id: 'p52',
    name: 'James Madison',
    type: 'Person',
    description: 'An American statesman, diplomat, expansionist, philosopher, and Founding Father who served as the fourth president of the United States from 1809 to 1817.',
    imageUrl: 'https://picsum.photos/seed/madison/500/500',
    hint: 'fourth president',
  },
  {
    id: 'p53',
    name: 'George III',
    type: 'Person',
    description: 'King of Great Britain and Ireland from 25 October 1760 until the union of the two kingdoms on 1 January 1801, after which he was King of the United Kingdom of Great Britain and Ireland until his death.',
    imageUrl: 'https://picsum.photos/seed/george_iii/500/500',
    hint: 'british king',
  },
  {
    id: 'p54',
    name: 'Harry S Truman',
    type: 'Person',
    description: 'The 33rd president of the United States, serving from 1945 to 1953. He led the country through the final stages of World War II and the early years of the Cold War.',
    imageUrl: 'https://picsum.photos/seed/truman/500/500',
    hint: '33rd president',
  },
  {
    id: 'p55',
    name: 'George Washington',
    type: 'Person',
    description: 'The first President of the United States, Commander-in-Chief of the Continental Army during the American Revolutionary War, and one of the Founding Fathers.',
    imageUrl: 'https://picsum.photos/seed/washington/500/500',
    hint: 'first president',
  },
  {
    id: 'p56',
    name: 'US President (generic)',
    type: 'Person',
    description: 'Represents any President of the United States. Their leadership and decisions shape the course of the nation.',
    imageUrl: 'https://picsum.photos/seed/us_prez/500/500',
    hint: 'us president',
  },
  {
    id: 'p57',
    name: 'Mahatma Gandhi',
    type: 'Person',
    description: 'An Indian lawyer, anti-colonial nationalist, and political ethicist, who employed nonviolent resistance to lead the successful campaign for India\'s independence from British rule.',
    imageUrl: 'https://picsum.photos/seed/gandhi/500/500',
    hint: 'indian leader',
  },
  {
    id: 'p58',
    name: 'Chief Sitting Bull',
    type: 'Person',
    description: 'A Hunkpapa Lakota leader who led his people during years of resistance against United States government policies.',
    imageUrl: 'https://picsum.photos/seed/sitting_bull/500/500',
    hint: 'lakota leader',
  },
  // Events
  {
    id: 'e01',
    name: 'The Renaissance',
    type: 'Event',
    description: 'A period of great cultural change and achievement in Europe that spanned from the 14th to the 17th century.',
    imageUrl: 'https://picsum.photos/seed/renaissance/500/500',
    hint: 'historical period',
  },
  {
    id: 'e02',
    name: 'Discovery of Radium',
    type: 'Event',
    description: 'The 1898 discovery by Marie and Pierre Curie, which revolutionized science and medicine.',
    imageUrl: 'https://picsum.photos/seed/radium/500/500',
    hint: 'scientific breakthrough',
  },
  {
    id: 'e03',
    name: 'Crossing the Rubicon',
    type: 'Event',
    description: "A pivotal moment in 49 BC when Julius Caesar's army crossed the river, marking a point of no return.",
    imageUrl: 'https://picsum.photos/seed/rubicon/500/500',
    hint: 'ancient battle',
  },
  {
    id: 'e04',
    name: 'Ptolemaic Dynasty',
    type: 'Event',
    description: 'A Hellenistic kingdom based in ancient Egypt, founded by Ptolemy I Soter, a companion of Alexander the Great.',
    imageUrl: 'https://picsum.photos/seed/ptolemy/500/500',
    hint: 'ancient dynasty',
  },
  {
    id: 'e05',
    name: 'Manhattan Project',
    type: 'Event',
    description: 'A top-secret research and development undertaking during World War II that produced the first nuclear weapons.',
    imageUrl: 'https://picsum.photos/seed/manhattan/500/500',
    hint: 'wartime project',
  },
  {
    id: 'e06',
    name: 'Scientific Revolution',
    type: 'Event',
    description: 'A series of events that marked the emergence of modern science during the early modern period.',
    imageUrl: 'https://picsum.photos/seed/science_rev/500/500',
    hint: 'intellectual movement',
  },
  {
    id: 'e07',
    name: 'March on Washington',
    type: 'Event',
    description: 'A massive protest march in August 1963, where Martin Luther King Jr. delivered his famous "I Have a Dream" speech.',
    imageUrl: 'https://picsum.photos/seed/march/500/500',
    hint: 'protest march',
  },
  {
    id: 'e08',
    name: 'War of the Currents',
    type: 'Event',
    description: 'A series of events surrounding the introduction of competing electric power transmission systems in the late 1880s and early 1990s.',
    imageUrl: 'https://picsum.photos/seed/currents/500/500',
    hint: 'technological rivalry',
  },
  {
    id: 'e09',
    name: 'Analytical Engine',
    type: 'Event',
    description: 'A proposed mechanical general-purpose computer designed by English mathematician and computer pioneer Charles Babbage.',
    imageUrl: 'https://picsum.photos/seed/engine/500/500',
    hint: 'early computer',
  },
  {
    id: 'e10',
    name: 'The Copernican Model',
    type: 'Event',
    description: 'A model of the universe that placed the Sun, rather than Earth, at the center of the universe.',
    imageUrl: 'https://picsum.photos/seed/copernicus/500/500',
    hint: 'astronomy model',
  },
  {
    id: 'e11',
    name: '100 Years War',
    type: 'Event',
    description: 'A series of conflicts from 1337 to 1453 between the House of Plantagenet of England and the House of Valois of France.',
    imageUrl: 'https://picsum.photos/seed/100_years_war/500/500',
    hint: 'medieval war',
  },
  {
    id: 'e12',
    name: 'Treaty of Paris (1783)',
    type: 'Event',
    description: 'The peace agreement that officially ended the American Revolution. Britain recognized American independence and cede territory to the new United States.',
    imageUrl: 'https://picsum.photos/seed/treaty/500/500',
    hint: 'peace treaty',
  },
  {
    id: 'e13',
    name: 'Boston Tea Party',
    type: 'Event',
    description: 'In December 1773, American colonists disguised as Mohawk Indians dumped tea into Boston Harbor to protest the Tea Act and British taxation without representation.',
    imageUrl: 'https://picsum.photos/seed/tea_party/500/500',
    hint: 'american revolution',
  },
  {
    id: 'e14',
    name: 'Shot Heard Round the World',
    type: 'Event',
    description: 'The opening battles of the American Revolution in April 1775. British troops clashed with colonial militias at Lexington and Concord, marking the official start of the war.',
    imageUrl: 'https://picsum.photos/seed/lexington/500/500',
    hint: 'revolutionary war',
  },
  {
    id: 'e15',
    name: 'Human Rights Movement',
    type: 'Event',
    description: 'A social movement dedicated to securing and protecting the fundamental rights and freedoms for all individuals.',
    imageUrl: 'https://picsum.photos/seed/human_rights/500/500',
    hint: 'human rights',
  },
  {
    id: 'e16',
    name: 'Social Influence',
    type: 'Event',
    description: 'The process by which individuals\' attitudes, beliefs or behavior are modified by the presence or action of others.',
    imageUrl: 'https://picsum.photos/seed/social/500/500',
    hint: 'social movement',
  },
  {
    id: 'e17',
    name: 'Conservation',
    type: 'Event',
    description: 'The movement to protect animals, plants, and natural resources.',
    imageUrl: 'https://picsum.photos/seed/nature/500/500',
    hint: 'nature protection',
  },
  {
    id: 'e18',
    name: 'Panama Canal',
    type: 'Event',
    description: 'A 48-mile artificial waterway in Panama that connects the Atlantic Ocean with the Pacific Ocean. The canal cuts across the Isthmus of Panama and is a conduit for maritime trade.',
    imageUrl: 'https://picsum.photos/seed/canal/500/500',
    hint: 'maritime trade',
  },
  {
    id: 'e19',
    name: 'Universal Declaration of Human Rights',
    type: 'Event',
    description: 'An international document adopted by the United Nations General Assembly that enshrines the rights and freedoms of all human beings.',
    imageUrl: 'https://picsum.photos/seed/declaration/500/500',
    hint: 'un document',
  },
  {
    id: 'e20',
    name: 'Fireside Chats',
    type: 'Event',
    description: 'A series of evening radio addresses given by U.S. President Franklin D. Roosevelt between 1933 and 1944.',
    imageUrl: 'https://picsum.photos/seed/chats/500/500',
    hint: 'radio address',
  },
  {
    id: 'e21',
    name: 'Abolitionist Movement',
    type: 'Event',
    description: 'The movement to end slavery, this term can be used both formally and informally.',
    imageUrl: 'https://picsum.photos/seed/abolition/500/500',
    hint: 'anti-slavery movement',
  },
  {
    id: 'e22',
    name: 'The Underground Railroad',
    type: 'Event',
    description: 'A network of secret routes and safe houses established in the United States during the mid-19th century, used by enslaved African-Americans to escape into free states and Canada.',
    imageUrl: 'https://picsum.photos/seed/railroad/500/500',
    hint: 'secret routes',
  },
  {
    id: 'e23',
    name: 'Apartheid',
    type: 'Event',
    description: 'A system of institutionalised racial segregation that existed in South Africa and South West Africa from 1948 until the early 1990s.',
    imageUrl: 'https://picsum.photos/seed/apartheid/500/500',
    hint: 'racial segregation',
  },
  {
    id: 'e24',
    name: 'World War II',
    type: 'Event',
    description: 'A global war that lasted from 1939 to 1945. It involved the vast majority of the world\'s countries—including all the great powers.',
    imageUrl: 'https://picsum.photos/seed/wwii/500/500',
    hint: 'global war',
  },
  {
    id: 'e25',
    name: 'The Mongol Empire',
    type: 'Event',
    description: 'Existed during the 13th and 14th centuries and was the largest contiguous land empire in history.',
    imageUrl: 'https://picsum.photos/seed/mongol/500/500',
    hint: 'land empire',
  },
  {
    id: 'e26',
    name: 'Frequency Hopping',
    type: 'Event',
    description: 'The method of changing communication frequencies to prevent interception, co-invented by Hedy Lamarr.',
    imageUrl: 'https://picsum.photos/seed/frequency/500/500',
    hint: 'radio technology',
  },
  {
    id: 'e27',
    name: 'The Napoleonic Wars',
    type: 'Event',
    description: 'A series of major conflicts pitting the French Empire and its allies, led by Napoleon I, against a fluctuating array of European powers formed into various coalitions.',
    imageUrl: 'https://picsum.photos/seed/napoleon_wars/500/500',
    hint: 'european conflicts',
  },
  {
    id: 'e28',
    name: 'The Globe Theatre',
    type: 'Event',
    description: 'A theatre in London associated with William Shakespeare. It was built in 1599 by Shakespeare\'s playing company, the Lord Chamberlain\'s Men.',
    imageUrl: 'https://picsum.photos/seed/globe/500/500',
    hint: 'london theatre',
  },
  {
    id: 'e29',
    name: 'Age of Discovery',
    type: 'Event',
    description: 'A period of European global exploration that started in the early 15th century. It marks the time in which extensive overseas exploration emerged as a powerful factor in European culture.',
    imageUrl: 'https://picsum.photos/seed/discovery/500/500',
    hint: 'global exploration',
  },
  {
    id: 'e30',
    name: 'The Space Race',
    type: 'Event',
    description: 'A 20th-century competition between two Cold War rivals, the Soviet Union (USSR) and the United States (US), for supremacy in spaceflight capability.',
    imageUrl: 'https://picsum.photos/seed/space/500/500',
    hint: 'space competition',
  },
  {
    id: 'e31',
    name: 'Apollo 11 Mission',
    type: 'Event',
    description: 'The spaceflight that first landed humans on the Moon. Commander Neil Armstrong and lunar module pilot Buzz Aldrin formed the American crew that landed the Apollo Lunar Module Eagle on July 20, 1969.',
    imageUrl: 'https://picsum.photos/seed/apollo/500/500',
    hint: 'moon landing',
  },
  {
    id: 'e32',
    name: 'Golden Age of Aviation',
    type: 'Event',
    description: 'The period in the history of aviation between the end of World War I and the beginning of World War II.',
    imageUrl: 'https://picsum.photos/seed/aviation/500/500',
    hint: 'aviation history',
  },
  {
    id: 'e33',
    name: 'The Silk Road',
    type: 'Event',
    description: 'A network of trade routes which connected the East and West, and was central to the economic, cultural, political, and religious interactions between these regions from the 2nd century BCE to the 18th century.',
    imageUrl: 'https://picsum.photos/seed/silk_road/500/500',
    hint: 'trade routes',
  },
  {
    id: 'e34',
    name: 'The Federalist Papers',
    type: 'Event',
    description: 'A collection of 85 articles and essays written by Alexander Hamilton, James Madison, and John Jay under the pseudonym "Publius" to promote the ratification of the United States Constitution.',
    imageUrl: 'https://picsum.photos/seed/federalist/500/500',
    hint: 'political essays',
  },
  {
    id: 'e35',
    name: 'Louisiana Purchase',
    type: 'Event',
    description: 'The acquisition of the territory of Louisiana by the United States from France in 1803.',
    imageUrl: 'https://picsum.photos/seed/louisiana/500/500',
    hint: 'territory acquisition',
  },
  {
    id: 'e36',
    name: 'The American Civil War',
    type: 'Event',
    description: 'A civil war in the United States from 1861 to 1865, fought between the Union and the Confederacy.',
    imageUrl: 'https://picsum.photos/seed/civil_war/500/500',
    hint: 'us civil',
  },
  {
    id: 'e37',
    name: 'The New Deal',
    type: 'Event',
    description: 'A series of programs, public work projects, financial reforms, and regulations enacted by President Franklin D. Roosevelt in the United States between 1933 and 1939.',
    imageUrl: 'https://picsum.photos/seed/new_deal/500/500',
    hint: 'public work',
  },
  {
    id: 'e38',
    name: 'Women\'s Suffrage Movement',
    type: 'Event',
    description: 'The struggle for the right of women to vote and run for office and is part of the overall women\'s rights movement.',
    imageUrl: 'https://picsum.photos/seed/suffrage/500/500',
    hint: 'women rights',
  },
  {
    id: 'e39',
    name: 'Theory of Evolution',
    type: 'Event',
    description: 'The scientific theory that explains the process of change over time by which modern organisms have descended from ancient organisms.',
    imageUrl: 'https://picsum.photos/seed/evolution/500/500',
    hint: 'scientific theory',
  },
  {
    id: 'e40',
    name: 'Post-Impressionism',
    type: 'Event',
    description: 'A predominantly French art movement that developed roughly between 1886 and 1905, from the last Impressionist exhibition to the birth of Fauvism.',
    imageUrl: 'https://picsum.photos/seed/post_impression/500/500',
    hint: 'art movement',
  },
  {
    id: 'e41',
    name: 'The Progressive Era',
    type: 'Event',
    description: 'A period of widespread social activism and political reform across the United States that spanned the 1890s to the 1920s.',
    imageUrl: 'https://picsum.photos/seed/progressive/500/500',
    hint: 'social activism',
  },
  {
    id: 'e42',
    name: 'Globalization',
    type: 'Event',
    description: 'The process of interaction and integration among people, companies, and governments worldwide.',
    imageUrl: 'https://picsum.photos/seed/global/500/500',
    hint: 'global interaction',
  },
  {
    id: 'e43',
    name: 'Montgomery Bus Boycott',
    type: 'Event',
    description: 'A political and social protest campaign against the policy of racial segregation on the public transit system of Montgomery, Alabama.',
    imageUrl: 'https://picsum.photos/seed/boycott/500/500',
    hint: 'protest campaign',
  },
  {
    id: 'e44',
    name: 'Imprisonment and Resistance',
    type: 'Event',
    description: 'Represents the act of being confined as a punishment for a crime or for political opposition, and the struggle against such confinement.',
    imageUrl: 'https://picsum.photos/seed/resistance/500/500',
    hint: 'political struggle',
  },
  {
    id: 'e45',
    name: 'Declaration of Independence',
    type: 'Event',
    description: 'The pronouncement adopted by the Second Continental Congress meeting in Philadelphia, Pennsylvania, on July 4, 1776.',
    imageUrl: 'https://picsum.photos/seed/independence/500/500',
    hint: 'historic document',
  },
  {
    id: 'e46',
    name: 'Founding Fathers',
    type: 'Event',
    description: 'A group of American leaders who united the Thirteen Colonies, led the war for independence from Great Britain, and built a frame of government for the new United States of America.',
    imageUrl: 'https://picsum.photos/seed/founders/500/500',
    hint: 'american leaders',
  },
  {
    id: 'e47',
    name: 'War (generic)',
    type: 'Event',
    description: 'A state of armed conflict between different nations or states or different groups within a nation or state.',
    imageUrl: 'https://picsum.photos/seed/war/500/500',
    hint: 'armed conflict',
  },
  {
    id: 'e48',
    name: 'Treasury System',
    type: 'Event',
    description: 'The system of financial management of a country, including the collection of revenue and the payment of government expenses.',
    imageUrl: 'https://picsum.photos/seed/treasury/500/500',
    hint: 'financial management',
  },
  {
    id: 'e49',
    name: 'World War I',
    type: 'Event',
    description: 'A global war originating in Europe that lasted from 28 July 1914 to 11 November 1918.',
    imageUrl: 'https://picsum.photos/seed/wwi/500/500',
    hint: 'global conflict',
  },
  {
    id: 'e50',
    name: 'Spanish Armada',
    type: 'Event',
    description: 'A Habsburg Spanish fleet of 130 ships that sailed from Corunna in late May 1588, with the purpose of escorting an army from Flanders to invade England.',
    imageUrl: 'https://picsum.photos/seed/armada/500/500',
    hint: 'spanish fleet',
  },
  {
    id: 'e51',
    name: 'English Reformation',
    type: 'Event',
    description: 'A series of events in 16th-century England by which the Church of England broke away from the authority of the Pope and the Roman Catholic Church.',
    imageUrl: 'https://picsum.photos/seed/reformation/500/500',
    hint: 'church breakaway',
  },
  {
    id: 'e52',
    name: 'Monarch (generic)',
    type: 'Event',
    description: 'Represents a sovereign head of state in a monarchy.',
    imageUrl: 'https://picsum.photos/seed/monarch/500/500',
    hint: 'sovereign ruler',
  },
  {
    id: 'e53',
    name: 'Elizabethan Era',
    type: 'Event',
    description: 'The epoch in the Tudor period of the history of England during the reign of Queen Elizabeth I (1558–1603).',
    imageUrl: 'https://picsum.photos/seed/elizabethan/500/500',
    hint: 'tudor period',
  },
  {
    id: 'e54',
    name: 'Revolution (generic)',
    type: 'Event',
    description: 'A fundamental and relatively sudden change in political power and political organization which occurs when the population revolts against the government.',
    imageUrl: 'https://picsum.photos/seed/rev/500/500',
    hint: 'political revolt',
  },
  {
    id: 'e55',
    name: 'French Revolution',
    type: 'Event',
    description: 'A period of far-reaching social and political upheaval in France and its colonies beginning in 1789.',
    imageUrl: 'https://picsum.photos/seed/french_rev/500/500',
    hint: 'social upheaval',
  },
  {
    id: 'e56',
    name: 'Patron of Exploration',
    type: 'Event',
    description: 'Represents a wealthy or powerful person who provides financial support to explorers.',
    imageUrl: 'https://picsum.photos/seed/patron/500/500',
    hint: 'explorer sponsor',
  },
  {
    id: 'e57',
    name: 'European Conquest',
    type: 'Event',
    description: 'The period of European colonization of the Americas, Africa, and Asia.',
    imageUrl: 'https://picsum.photos/seed/conquest/500/500',
    hint: 'european colonization',
  },
  {
    id: 'e58',
    name: 'Native Resistance',
    type: 'Event',
    description: 'The resistance of indigenous peoples to the European colonization.',
    imageUrl: 'https://picsum.photos/seed/native/500/500',
    hint: 'indigenous resistance',
  },
  {
    id: 'e59',
    name: 'Emperor of France',
    type: 'Event',
    description: 'Title held by the monarchs of the First and Second French Empires.',
    imageUrl: 'https://picsum.photos/seed/emperor/500/500',
    hint: 'french monarch',
  },
  {
    id: 'e60',
    name: 'Roman Alliances',
    type: 'Event',
    description: 'The political and military agreements between the Roman Republic/Empire and other states.',
    imageUrl: 'https://picsum.photos/seed/allies/500/500',
    hint: 'roman agreements',
  },
  {
    id: 'e61',
    name: 'Vice President (generic)',
    type: 'Event',
    description: 'An officer in government or business who is below a president in rank.',
    imageUrl: 'https://picsum.photos/seed/vp/500/500',
    hint: 'government officer',
  },
  {
    id: 'e62',
    name: 'Crusades',
    type: 'Event',
    description: 'A series of religious wars initiated, supported, and sometimes directed by the Latin Church in the medieval period.',
    imageUrl: 'https://picsum.photos/seed/crusades/500/500',
    hint: 'religious wars',
  },
  {
    id: 'e63',
    name: 'I Have a Dream Speech',
    type: 'Event',
    description: 'A public speech that was delivered by American civil rights activist Martin Luther King Jr. during the March on Washington for Jobs and Freedom on August 28, 1963.',
    imageUrl: 'https://picsum.photos/seed/speech/500/500',
    hint: 'public speech',
  },
  {
    id: 'e64',
    name: 'Emancipation Proclamation',
    type: 'Event',
    description: 'A presidential proclamation and executive order issued by United States President Abraham Lincoln on January 1, 1863.',
    imageUrl: 'https://picsum.photos/seed/proclamation/500/500',
    hint: 'presidential proclamation',
  },
  {
    id: 'e65',
    name: 'Federal Reserve Creation',
    type: 'Event',
    description: 'The establishment of the central banking system of the United States, which was created on December 23, 1913, with the enactment of the Federal Reserve Act.',
    imageUrl: 'https://picsum.photos/seed/fed/500/500',
    hint: 'central banking',
  },
  {
    id: 'e121',
    name: 'Vietnam War',
    type: 'Event',
    description: 'A long, costly and divisive conflict that pitted the communist government of North Vietnam against South Vietnam and its principal ally, the United States.',
    imageUrl: 'https://picsum.photos/seed/vietnam/500/500',
    hint: 'cold war conflict',
  },
  {
    id: 'e122',
    name: 'Cuban Missile Crisis',
    type: 'Event',
    description: 'A 13-day confrontation between the United States and the Soviet Union in October 1962, which escalated the Cold War.',
    imageUrl: 'https://picsum.photos/seed/cuban/500/500',
    hint: 'cold war confrontation',
  },
  {
    id: 'e123',
    name: 'Red Scare',
    type: 'Event',
    description: 'A period of widespread fear of a potential rise of communism or anarchism by a society or state. Two major Red Scares occurred in the United States.',
    imageUrl: 'https://picsum.photos/seed/red_scare/500/500',
    hint: 'communism fear',
  },
  {
    id: 'e124',
    name: 'Draft (generic)',
    type: 'Event',
    description: 'Compulsory recruitment for military service. It has been used in various countries and conflicts throughout history.',
    imageUrl: 'https://picsum.photos/seed/draft/500/500',
    hint: 'military recruitment',
  },
  {
    id: 'e66',
    name: 'Indian Independence Movement',
    type: 'Event',
    description: 'A series of historic events with the ultimate aim of ending British rule in India. It lasted from 1857 to 1947.',
    imageUrl: 'https://picsum.photos/seed/india/500/500',
    hint: 'indian independence',
  },
  {
    id: 'e67',
    name: 'Salt March',
    type: 'Event',
    description: 'An act of nonviolent civil disobedience in colonial India led by Mahatma Gandhi.',
    imageUrl: 'https://picsum.photos/seed/salt/500/500',
    hint: 'gandhi protest',
  },
  {
    id: 'e68',
    name: 'Russian Empire Expansion',
    type: 'Event',
    description: 'The territorial growth of Russia from the 16th to the 20th century, covering vast areas of Eurasia.',
    imageUrl: 'https://picsum.photos/seed/russia/500/500',
    hint: 'empire expansion',
  },
  {
    id: 'e69',
    name: 'Macedonian Conquests',
    type: 'Event',
    description: 'The military campaigns of Alexander the Great, which established one of the largest empires in the ancient world.',
    imageUrl: 'https://picsum.photos/seed/macedon/500/500',
    hint: 'ancient campaigns',
  },
  {
    id: 'e70',
    name: 'Anti-Apartheid Movement',
    type: 'Event',
    description: 'A global movement to oppose the system of racial segregation in South Africa, leading to its eventual downfall.',
    imageUrl: 'https://picsum.photos/seed/anti_apartheid/500/500',
    hint: 'global movement',
  },
  {
    id: 'e71',
    name: 'Church of England',
    type: 'Event',
    description: 'The established church of England, which separated from the Roman Catholic Church during the English Reformation.',
    imageUrl: 'https://picsum.photos/seed/c_of_e/500/500',
    hint: 'english church',
  },
  {
    id: 'e72',
    name: 'Basic Religion',
    type: 'Event',
    description: 'Represents the fundamental principles and practices of a major world religion, influencing culture, law, and society.',
    imageUrl: 'https://picsum.photos/seed/religion/500/500',
    hint: 'religion symbol',
  },
  {
    id: 'e73',
    name: 'French Nationalism',
    type: 'Event',
    description: 'A political ideology that promotes the unity and interests of the French nation, often associated with the French Revolution and Napoleon.',
    imageUrl: 'https://picsum.photos/seed/nationalism/500/500',
    hint: 'political ideology',
  },
  {
    id: 'e74',
    name: 'Tudor Dynasty',
    type: 'Event',
    description: 'A royal house of Welsh origin that ruled England from 1485 to 1603, including monarchs like Henry VIII and Elizabeth I.',
    imageUrl: 'https://picsum.photos/seed/tudor/500/500',
    hint: 'royal house',
  },
  {
    id: 'e75',
    name: 'Monarchy Reforms',
    type: 'Event',
    description: 'Represents significant changes to the powers, structure, or role of a monarchy, often leading to constitutional monarchy.',
    imageUrl: 'https://picsum.photos/seed/monarch_reform/500/500',
    hint: 'government reform',
  },
  {
    id: 'e76',
    name: 'Reconciliation',
    type: 'Event',
    description: 'The process of restoring friendly relations, often after a period of conflict or war, such as post-apartheid South Africa.',
    imageUrl: 'https://picsum.photos/seed/peace/500/500',
    hint: 'restoring peace',
  },
  {
    id: 'e77',
    name: 'Cold War Influence',
    type: 'Event',
    description: 'Represents the global ideological, political, and economic influence exerted by the US and the Soviet Union after WWII.',
    imageUrl: 'https://picsum.photos/seed/cold_war/500/500',
    hint: 'global influence',
  },
  {
    id: 'e78',
    name: 'Non-Violent Resistance',
    type: 'Event',
    description: 'The practice of achieving goals such as social change through symbolic protests, civil disobedience, or other methods, without using violence.',
    imageUrl: 'https://picsum.photos/seed/non_violence/500/500',
    hint: 'peaceful protest',
  },
  {
    id: 'e79',
    name: 'Cultural Power',
    type: 'Event',
    description: 'Represents the influence of a nation\'s or region\'s culture on others, often referred to as "soft power".',
    imageUrl: 'https://picsum.photos/seed/soft_power/500/500',
    hint: 'cultural influence',
  },
  {
    id: 'e80',
    name: 'Cultural Spread',
    type: 'Event',
    description: 'The expansion and adoption of cultural elements, such as ideas, styles, religions, technologies, and languages.',
    imageUrl: 'https://picsum.photos/seed/culture/500/500',
    hint: 'cultural diffusion',
  },
  {
    id: 'e93',
    name: 'UN Advocacy',
    type: 'Event',
    description: 'Represents efforts to influence the United Nations on various global issues, from human rights to climate change.',
    imageUrl: 'https://picsum.photos/seed/un/500/500',
    hint: 'un advocacy',
  },
  {
    id: 'e94',
    name: 'Atomic Bomb Decisions',
    type: 'Event',
    description: 'The complex and controversial decisions surrounding the use of atomic weapons during World War II, involving figures like Truman and Einstein.',
    imageUrl: 'https://picsum.photos/seed/atom/500/500',
    hint: 'atomic bomb',
  },
  {
    id: 'e95',
    name: 'Early Republic Politics',
    type: 'Event',
    description: 'The political landscape of the United States in its early years, marked by debates between Federalists and Democratic-Republicans.',
    imageUrl: 'https://picsum.photos/seed/politics/500/500',
    hint: 'republic politics',
  },
  {
    id: 'e96',
    name: 'Lewis and Clark Expedition',
    type: 'Event',
    description: 'The first American expedition to cross the western portion of the United States, departing in May 1804.',
    imageUrl: 'https://picsum.photos/seed/lewis_clark/500/500',
    hint: 'lewis clark',
  },
  {
    id: 'e97',
    name: 'Famous Speech',
    type: 'Event',
    description: 'This person is famous for a speech they made.',
    imageUrl: 'https://picsum.photos/seed/famous_speech/500/500',
    hint: 'famous speech',
  },
  {
    id: 'e98',
    name: 'American Revolution',
    type: 'Event',
    description: 'A colonial revolt that took place between 1765 and 1783. The American Patriots in the Thirteen Colonies won independence from Great Britain, becoming the United States of America.',
    imageUrl: 'https://picsum.photos/seed/revolution/500/500',
    hint: 'colonial revolt',
  },
  {
    id: 'e99',
    name: 'Constitution',
    type: 'Event',
    description: 'Represents the fundamental principles or established precedents according to which a state or other organization is acknowledged to be governed.',
    imageUrl: 'https://picsum.photos/seed/constitution/500/500',
    hint: 'historic constitution',
  },
  {
    id: 'e100',
    name: 'Duel',
    type: 'Event',
    description: 'An arranged engagement in combat between two individuals, with matched weapons in accordance with agreed-upon rules.',
    imageUrl: 'https://picsum.photos/seed/duel/500/500',
    hint: 'combat duel',
  },
  {
    id: 'e101',
    name: 'American Flag Creation',
    type: 'Event',
    description: 'The act of creating the first official flag of the United States, often attributed to Betsy Ross.',
    imageUrl: 'https://picsum.photos/seed/flag/500/500',
    hint: 'flag creation',
  },
  {
    id: 'e129',
    name: 'Enlightenment Influence',
    type: 'Event',
    description: 'Represents the influence of the Enlightenment, a major intellectual and philosophical movement that dominated the world of ideas in Europe during the 17th and 18th centuries.',
    imageUrl: 'https://picsum.photos/seed/enlightenment/500/500',
    hint: 'intellectual movement',
  },
  {
    id: 'e130',
    name: 'Empire Building',
    type: 'Event',
    description: 'The process of forming and maintaining an empire through colonization, conquest, or economic domination.',
    imageUrl: 'https://picsum.photos/seed/empire/500/500',
    hint: 'empire building',
  },
  {
    id: 'e131',
    name: 'Regency Era',
    type: 'Event',
    description: 'A period at the end of the Georgian era, during which King George III was deemed unfit to rule and his son ruled as his proxy as Prince Regent.',
    imageUrl: 'https://picsum.photos/seed/regency_period/500/500',
    hint: 'georgian era',
  },
  {
    id: 'e132',
    name: 'Structure of DNA',
    type: 'Event',
    description: 'The discovery of the double helix structure of DNA, a monumental breakthrough in the history of science.',
    imageUrl: 'https://picsum.photos/seed/dna_helix/500/500',
    hint: 'dna discovery',
  },
  // Wildcards
  {
    id: 'w01',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Use this card as any historical Person or Event to complete your Hist Set.',
    imageUrl: 'https://picsum.photos/seed/wildcard_1/500/500',
    hint: 'mysterious magic',
  },
  {
    id: 'w02',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Use this card as any historical Person or Event to complete your Hist Set.',
    imageUrl: 'https://picsum.photos/seed/wildcard_2/500/500',
    hint: 'mysterious magic',
  },
  {
    id: 'w03',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Use this card as any historical Person or Event to complete your Hist Set.',
    imageUrl: 'https://picsum.photos/seed/wildcard_3/500/500',
    hint: 'mysterious magic',
  },
  {
    id: 'w04',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Use this card as any historical Person or Event to complete your Hist Set.',
    imageUrl: 'https://picsum.photos/seed/wildcard_4/500/500',
    hint: 'mysterious magic',
  },
];