import type { Card } from './types';
import images from '@/app/lib/placeholder-images.json';

export const DECK: Card[] = [
  {
    id: 'p01',
    name: 'Leonardo da Vinci',
    type: 'Person',
    description: 'A true Renaissance man, excelling in painting, sculpture, architecture, and science.',
    imageUrl: images.leonardo_da_vinci,
    hint: 'renaissance artist',
  },
  {
    id: 'p02',
    name: 'Marie Curie',
    type: 'Person',
    description: 'Pioneering researcher on radioactivity and first woman to win a Nobel Prize.',
    imageUrl: images.marie_curie,
    hint: 'scientist radioactivity',
  },
  {
    id: 'p03',
    name: 'Julius Caesar',
    type: 'Person',
    description: 'Roman general and statesman who led the demise of the Roman Republic.',
    imageUrl: images.julius_caesar,
    hint: 'roman leader',
  },
  {
    id: 'p04',
    name: 'Susan B. Anthony',
    type: 'Person',
    description: 'Pivotal leader in the women\'s suffrage movement in the United States.',
    imageUrl: images.susan_b_anthony,
    hint: 'suffrage leader',
  },
  {
    id: 'e01',
    name: 'The Renaissance',
    type: 'Event',
    description: 'Period of great cultural achievement in Europe from the 14th to 17th century.',
    imageUrl: images.renaissance,
    hint: 'historical period',
  },
  {
    id: 'e02',
    name: 'Structure of DNA',
    type: 'Event',
    description: 'The discovery of the double helix structure, a breakthrough in genetic science.',
    imageUrl: images.dna_structure,
    hint: 'science discovery',
  },
  {
    id: 'e03',
    name: 'Regency Era',
    type: 'Event',
    description: 'A period in British history (1811–1820) known for its distinctive architecture and literature.',
    imageUrl: images.regency_era,
    hint: 'british history',
  },
  {
    id: 'w01',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Can be used as any historical Person or Event.',
    imageUrl: images.wildcard,
    hint: 'mysterious magic',
  },
  {
    id: 'w02',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Can be used as any historical Person or Event.',
    imageUrl: images.wildcard,
    hint: 'mysterious magic',
  },
  {
    id: 'w03',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Can be used as any historical Person or Event.',
    imageUrl: images.wildcard,
    hint: 'mysterious magic',
  },
  {
    id: 'w04',
    name: 'Chrono-Wildcard',
    type: 'Wildcard',
    description: 'A rift in time. Can be used as any historical Person or Event.',
    imageUrl: images.wildcard,
    hint: 'mysterious magic',
  },
  {
    id: 'p05',
    name: 'Albert Einstein',
    type: 'Person',
    description: 'Developed the theory of relativity, a pillar of modern physics.',
    imageUrl: images.einstein,
    hint: 'modern physicist',
  }
];
